### ISSUE TITLE
Adicionar token de aspas

### ISSUE THREAD

**Issue by angelasoler** [victorfmartins/minishell#12]
- Criar função
-

**Comment by victorfmartins** [comment]
Por enquanto temos apenas um código simples para as aspas simples. O que ele faz e tratar nomes estranhos de arquivos que necessitam de aspas.

**Comment by victorfmartins** [comment]
Add codigo para aspas duplas. Agr precisamos apenas fazer a expansão do que for necessario considerando a função das aspas. Vou criar um novo issue para isso.
